#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/hashmap
src/pointerarray
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_mulle-concurrent-include-private.h
)

set( PRIVATE_HEADERS
src/include-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_mulle-concurrent-include.h
)

set( PUBLIC_HEADERS
src/hashmap/mulle-concurrent-hashmap.h
src/include.h
src/mulle-concurrent.h
src/mulle-concurrent-types.h
src/pointerarray/mulle-concurrent-pointerarray.h
)

