# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/resources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

message( STATUS " No resources found. `mulle-sde environment set MULLE_MATCH_TO_CMAKE_RESOURCES_FILE NONE`, to avoid this (harmless) warning")
