#
# This file will be included by cmake/share/resources.cmake
#
# cmake/reflect/_Resources.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

message( STATUS " No resources found. `mulle-sde environment set MULLE_MATCH_TO_CMAKE_RESOURCES_FILE NONE`, to avoid this (harmless warning)")
