# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/hashmap/mulle-concurrent-hashmap.c
src/pointerarray/mulle-concurrent-pointerarray.c
)

#
# contents selected with patternfile ??-source--standalone-sources
#
set( STANDALONE_SOURCES
src/mulle-concurrent-standalone.c
)
