/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#ifndef mulle_concurrent_versioncheck_h__
#define mulle_concurrent_versioncheck_h__

#if defined( MULLE__ABA_VERSION)
# ifndef MULLE__ABA_VERSION_MIN
#  define MULLE__ABA_VERSION_MIN  ((3UL << 20) | (1 << 8) | 1)
# endif
# ifndef MULLE__ABA_VERSION_MAX
#  define MULLE__ABA_VERSION_MAX  ((4UL << 20) | (0 << 8) | 0)
# endif
# if MULLE__ABA_VERSION < MULLE__ABA_VERSION_MIN
#  error "mulle-aba is too old"
# endif
# if MULLE__ABA_VERSION >= MULLE__ABA_VERSION_MAX
#  error "mulle-aba is too new"
# endif
#endif

#endif
