/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_concurrent_include_private_h__
#define _mulle_concurrent_include_private_h__

/* no headers */

#endif
