/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost. Suppress this file with:

   mulle-sde environment set MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE DISABLE
*/
#ifndef _mulle_concurrent_include_private_h__
#define _mulle_concurrent_include_private_h__

/* no headers */

#endif
