/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_concurrent_include_h__
#define _mulle_concurrent_include_h__

// remove with `mulle-sourcetree mark mulle-aba no-header`
// rename with `mulle-sourcetree mark mulle-aba set include whatever.h`
# include <mulle-aba/mulle-aba.h>   // mulle-aba

#endif
