#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/hashmap
src/pointerarray
) 

set( PRIVATE_HEADERS
src/include-private.h
)

set( PUBLIC_HEADERS
src/hashmap/mulle-concurrent-hashmap.h
src/include.h
src/mulle-concurrent.h
src/mulle-concurrent-types.h
src/pointerarray/mulle-concurrent-pointerarray.h
) 

