#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/hashmap/mulle-concurrent-hashmap.c
src/mulle-concurrent-standalone.c
src/pointerarray/mulle-concurrent-pointerarray.c
)
